version: '3.8'

services:
  solid-vpn:
    build: .
    container_name: solid-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - WG_CONFIG_DIR=/etc/wireguard
      - WG_INTERFACE=wg0
      - WG_DEFAULT_ADDRESS=
      - WG_PORT=51820
      - WG_HOST=
      - WG_DNS=
      - WG_ALLOWED_IPS=
      - FLASK_SECRET_KEY=
      - FLASK_LOGIN_PASSWORD=
    ports:
      - "80:80"
      - "51820:51820/udp"
    volumes:
      - /etc/wireguard:/etc/wireguard
    restart: unless-stopped
