version: '3.8'

services:
  solid-vpn:
    build: .
    container_name: solid-vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - WG_CONFIG_DIR=/etc/wireguard
      - WG_INTERFACE=wg0
      - WG_DEFAULT_ADDRESS=${wg_default_network}
      - WG_PORT=51820
      - WG_HOST=${tenant_external_ip}
      - WG_DNS=${tenant_dns}
      - WG_ALLOWED_IPS=${tenant_network}, ${wg_default_network}
      - FLASK_SECRET_KEY=${wg_admin_password}
      - FLASK_LOGIN_PASSWORD=${wg_admin_password}
    ports:
      - "80:80"
      - "51820:51820/udp"
    volumes:
      - /etc/wireguard:/etc/wireguard
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
